# Generated by Django 3.1.6 on 2021-02-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва тексту')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Досліджуванний текст')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='main.TagText', verbose_name='Тег')),
            ],
        ),
    ]
