# Generated by Django 3.1.6 on 2021-02-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='tag',
        ),
        migrations.AddField(
            model_name='text',
            name='texttag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
